### PR TITLE
:new: :art: [source_location] Source location for test

### PR DESCRIPTION
**Pull request by krzysztof-jusiak**
Problem:
-

Solution:
-

Issue: #

Reviewers:
@

### CODE REVIEW

**Comment by krzysztof-jusiak** [comment]
@lp55 -> This PR should work for both `"test"_test and test("test")` -> https://godbolt.org/z/hTDnXJ

**Comment by lp55** [comment]
Nice! :)
Simple and clever! Seems obvious now that it's done :D
Thanks! This makes integration with [ApprovalTests.cpp](https://github.com/approvals/ApprovalTests.cpp) much smoother.

**Comment by claremacrae** [comment]
Thanks for this!

Apologies if I’m missing anything obvious, but would it be worth adding a test that explicitly checks that the source name ends with ut/ut.cpp or ut\ut.cpp

**Comment by claremacrae** [comment]
Hi Kris, is there any possibility that this could be merged please? We plan to do a release of Approval Tests tomorrow morning (California time) and would be pleased to include support for this library, as @lp55 says it’s nearly ready!

**Comment by krzysztof-jusiak** [comment]
sure, I can merge it, I'll follow with more tests/examples/docs how to use it, but I'd love to see integration with ApprovalTests, so let's go with it for now :+1: Thanks for your work @claremacrae 
and @lp55, really appreciate it :)

**Comment by lp55** [comment]
Thanks @krzysztof-jusiak! I'm already using this at work :D So nice not to have to use macros, and the ability to create test dynamically based on the test data I make available to the application is very nice. UT and ApprovalTests produce a very good combination :)

**Comment by claremacrae** [comment]
Hi @krzysztof-jusiak - I echo those thanks!!

Also, just to let you know that UT is fully added to Approval Tests now, and working great - I've credited both you and @lp55 in the next release notes - current draft is here, and it also links to the current docs of the new feature:
https://github.com/approvals/ApprovalTests.cpp/blob/e3b488ef12c3f6011963a172234fea46685c1c67/build/relnotes_X.X.X.md

**Comment by krzysztof-jusiak** [comment]
That's great! Thank you @claremacrae, @lp55 for your awesome work. Will follow the release of ApprovalTests and add an integration to the UT website and the newest release :+1:

**Comment by claremacrae** [comment]
It's released - https://github.com/approvals/ApprovalTests.cpp/releases/tag/v.7.0.0

**Comment by krzysztof-jusiak** [comment]
Awesome! Thanks, @claremacrae.

Added `Integrations` sections pointing at `ApprovalTests` to the README.md overview -> https://github.com/boost-experimental/ut#overview

Thanks again :pray:

**Pull request merged**
